;this file for FamiTone2 library generated by text2data tool

game_audio_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; background1
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,225,187 ; loading

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $70 ;instrument $01
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $02
	.word @env2,@env0,@env0
	.byte $00
	.byte $70 ;instrument $03
	.word @env2,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$cc,$c9,$c6,$c3,$c0,$00,$05
@env2:
	.byte $c4,$c8,$cc,$cf,$cc,$c9,$c6,$c3,$c0,$00,$08


; background1
@song0ch0:
	.byte $fb,$08
@song0ch0loop:
@ref0:
	.byte $80,$4b,$53,$59,$63,$4b,$53,$59,$62,$81
	.byte $fd
	.word @song0ch0loop

; background1
@song0ch1:
@song0ch1loop:
@ref1:
	.byte $82,$3b,$41,$4b,$53,$3b,$41,$4b,$52,$81
	.byte $fd
	.word @song0ch1loop

; background1
@song0ch2:
@song0ch2loop:
@ref2:
	.byte $80,$32,$8d,$40,$8d
	.byte $fd
	.word @song0ch2loop

; background1
@song0ch3:
@song0ch3loop:
@ref3:
	.byte $81,$80,$09,$08,$97
	.byte $fd
	.word @song0ch3loop

; background1
@song0ch4:
@song0ch4loop:
@ref4:
	.byte $9f
	.byte $fd
	.word @song0ch4loop


; loading
@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref5:
	.byte $84,$4b,$53,$59,$61,$62,$ed
	.byte $fd
	.word @song1ch0loop

; loading
@song1ch1:
@song1ch1loop:
@ref6:
	.byte $86,$41,$4b,$53,$58,$f1
	.byte $fd
	.word @song1ch1loop

; loading
@song1ch2:
@song1ch2loop:
@ref7:
	.byte $86,$32,$f9,$83
	.byte $fd
	.word @song1ch2loop

; loading
@song1ch3:
@song1ch3loop:
@ref8:
	.byte $f9,$85
	.byte $fd
	.word @song1ch3loop

; loading
@song1ch4:
@song1ch4loop:
@ref9:
	.byte $f9,$85
	.byte $fd
	.word @song1ch4loop
