;this file for FamiTone2 library generated by text2data tool

loading_jingle_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; New song

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $70 ;instrument $01
	.word @env1,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$cc,$c9,$c6,$c3,$c0,$00,$05


; New song
@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$4b,$53,$59,$63,$4b,$53,$59,$62,$81
	.byte $fd
	.word @song0ch0loop

; New song
@song0ch1:
@song0ch1loop:
@ref1:
	.byte $82,$3b,$41,$4b,$53,$3b,$41,$4b,$52,$81
	.byte $fd
	.word @song0ch1loop

; New song
@song0ch2:
@song0ch2loop:
@ref2:
	.byte $80,$32,$8d,$40,$8d
	.byte $fd
	.word @song0ch2loop

; New song
@song0ch3:
@song0ch3loop:
@ref3:
	.byte $81,$80,$09,$08,$97
	.byte $fd
	.word @song0ch3loop

; New song
@song0ch4:
@song0ch4loop:
@ref4:
	.byte $9f
	.byte $fd
	.word @song0ch4loop
